sudo: required

dist: trusty
language: perl

addons:
    apt:
        packages:
            - ant
            - unzip
            - default-jdk
            - subversion

# Skip cpanm installation
install: []

script:
    - make validate_without_docker
