sudo: required

dist: xenial
language: perl

addons:
    apt:
        packages:
            - ant
            - ant-optional
            - unzip
            - default-jdk
            - subversion

# Skip cpanm installation
install: []

script:
    - make --version
    - make audit
